version: '3'
services:
  dynamodb.local:
    image: amazon/dynamodb-local
    container_name: dynamodb.local
    ports:
      - 8000:8000
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-inMemory']
  dynamodb.admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb.local-admin
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb.local:8000
    depends_on:
      - dynamodb.local
