service: spotify-history

frameworkVersion: '2'
useDotenv: true
configValidationMode: error
unresolvedVariablesNotificationMode: error

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local

custom:
  env: ${opt:stage,'stg'} # Define default stage
  prefix: ${self:custom.env}-${self:service}
  tableName: ${self:custom.prefix}-db
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
      heapInitial: 200m
      heapMax: 1g
      seed: false
      convertEmptyValues: true
    seed:
      test:
        sources:
          - table: ${self:custom.tableName}
            sources: [./test/payloads/dynamo-history.json]

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stackName: ${self:custom.prefix}-stack
  stage: ${self:custom.env}
  lambdaHashingVersion: 20201221
  versionFunctions: false
  eventBridge:
    useCloudFormation: true
  memorySize: 128
  timeout: 5
  logRetentionInDays: 7
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:PutItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.tableName}'

functions:
  spotify-history-lambda:
    name: ${self:custom.prefix}
    handler: src/index.handler
    events:
      - eventBridge:
          schedule: cron(0 * * * ? *) # Cron job to run every hour
    environment:
      TABLE_NAME: ${self:custom.tableName} # Dynamo table name
      CUSTOM_AWS_REGION: ${self:provider.region} # AWS_REGION is reserved so...
      STAGE: ${self:custom.env} # Stage
      CLIENT_ID: ${env:CLIENT_ID} # Spotify client id
      CLIENT_SECRET: ${env:CLIENT_SECRET} # Spotify client secret
      REFRESH_TOKEN: ${env:REFRESH_TOKEN} # Spotify refresh token

resources:
  Resources:
    SpotifyHistoryDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

package:
  patterns:
    - '!README.md'
    - '!tsconfig.client.json'
    - '!.env'
    - '!.nvmrc'
    - '!scripts/**'
