service: spotify-history

frameworkVersion: '2'
useDotenv: true
configValidationMode: error
unresolvedVariablesNotificationMode: error

plugins:
  - serverless-plugin-typescript

custom:
  env: ${opt:stage,'stg'}

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${self:custom.env} # Define default stage
  lambdaHashingVersion: 20201221
  versionFunctions: false
  eventBridge:
    useCloudFormation: true
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 5 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  logRetentionInDays: 7 # Set the default RetentionInDays for a CloudWatch LogGr
  environment:
    PUBLIC_TEST: Public 123
    STAGE: ${self:custom.env}
    BUCKET_NAME: ${self:custom.env}-${self:service}-bucket

functions:
  spotify-history-lambda:
    name: ${self:custom.env}-${self:service}
    handler: src/index.handler
    events:
      - eventBridge:
          schedule: rate(30 minutes)
    environment:
      STAGE: ${self:custom.env}
      NODE_ENV: ${self:custom.env}

package:
  exclude:
    - .git/**
    - README.md
    - .gitignore
