service: spotify-history

frameworkVersion: '2'
useDotenv: true
configValidationMode: error
unresolvedVariablesNotificationMode: error

plugins:
  - serverless-plugin-typescript

custom:
  env: ${opt:stage,'stg'} # Define default stage
  prefix: ${self:custom.env}-${self:service}

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stackName: ${self:custom.prefix}-stack
  stage: ${self:custom.env}
  lambdaHashingVersion: 20201221
  versionFunctions: false
  eventBridge:
    useCloudFormation: true
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  timeout: 5 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  logRetentionInDays: 7 # Set the default RetentionInDays for a CloudWatch LogGr
  environment:
    PUBLIC_TEST: Public 123

functions:
  spotify-history-lambda:
    name: ${self:custom.prefix}
    handler: src/index.handler
    events:
      - eventBridge:
          schedule: rate(60 minutes)
    environment:
      STAGE: ${self:custom.env}
      NODE_ENV: ${self:custom.env}
      CLIENT_ID: ${env:CLIENT_ID}
      CLIENT_SECRET: ${env:CLIENT_SECRET}
      REFRESH_TOKEN: ${env:REFRESH_TOKEN}
      MONGO_PW: ${env:MONGO_PW}
      MONGO_USER: ${env:MONGO_USER}

package:
  exclude:
    - .git/**
    - README.md
    - .gitignore
