// Resonse from the Spotify API for endpoint:
// https://api.spotify.com/v1/me/player/recently-played

export default {
  items: [
    {
      track: {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/07h2T3RrXQzYW5YpQnXd8U',
              },
              href: 'https://api.spotify.com/v1/artists/07h2T3RrXQzYW5YpQnXd8U',
              id: '07h2T3RrXQzYW5YpQnXd8U',
              name: 'Breitbild',
              type: 'artist',
              uri: 'spotify:artist:07h2T3RrXQzYW5YpQnXd8U',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/4VhSnH6nevOLKaOgra164h',
          },
          href: 'https://api.spotify.com/v1/albums/4VhSnH6nevOLKaOgra164h',
          id: '4VhSnH6nevOLKaOgra164h',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b273b9ccd6f97f5b176ebcdf460c',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e02b9ccd6f97f5b176ebcdf460c',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d00004851b9ccd6f97f5b176ebcdf460c',
              width: 64,
            },
          ],
          name: 'Breitbild',
          release_date: '2016-03-18',
          release_date_precision: 'day',
          total_tracks: 11,
          type: 'album',
          uri: 'spotify:album:4VhSnH6nevOLKaOgra164h',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/07h2T3RrXQzYW5YpQnXd8U',
            },
            href: 'https://api.spotify.com/v1/artists/07h2T3RrXQzYW5YpQnXd8U',
            id: '07h2T3RrXQzYW5YpQnXd8U',
            name: 'Breitbild',
            type: 'artist',
            uri: 'spotify:artist:07h2T3RrXQzYW5YpQnXd8U',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 272193,
        explicit: false,
        external_ids: {
          isrc: 'CH0011600003',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/6EutORD6aSD4ms6w17r2js',
        },
        href: 'https://api.spotify.com/v1/tracks/6EutORD6aSD4ms6w17r2js',
        id: '6EutORD6aSD4ms6w17r2js',
        is_local: false,
        name: 'Einsam',
        popularity: 18,
        preview_url:
          'https://p.scdn.co/mp3-preview/bcaeffc785f91d13d69ca270df01c69a1dddd422?cid=38b0480fd0224dc187294a0730ee8098',
        track_number: 3,
        type: 'track',
        uri: 'spotify:track:6EutORD6aSD4ms6w17r2js',
      },
      played_at: '2021-09-04T15:20:19.797Z',
      context: null,
    },
    {
      track: {
        album: {
          album_type: 'album',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0tMFcqLXhtm1Gep20iuIR3',
              },
              href: 'https://api.spotify.com/v1/artists/0tMFcqLXhtm1Gep20iuIR3',
              id: '0tMFcqLXhtm1Gep20iuIR3',
              name: 'SXTN',
              type: 'artist',
              uri: 'spotify:artist:0tMFcqLXhtm1Gep20iuIR3',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CW',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IL',
            'IN',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/3GFtNDpTMjFmmPNVGI202h',
          },
          href: 'https://api.spotify.com/v1/albums/3GFtNDpTMjFmmPNVGI202h',
          id: '3GFtNDpTMjFmmPNVGI202h',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b2733339cc5ec85884a26e6ab9af',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e023339cc5ec85884a26e6ab9af',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d000048513339cc5ec85884a26e6ab9af',
              width: 64,
            },
          ],
          name: 'Leben am Limit',
          release_date: '2017-06-02',
          release_date_precision: 'day',
          total_tracks: 24,
          type: 'album',
          uri: 'spotify:album:3GFtNDpTMjFmmPNVGI202h',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0tMFcqLXhtm1Gep20iuIR3',
            },
            href: 'https://api.spotify.com/v1/artists/0tMFcqLXhtm1Gep20iuIR3',
            id: '0tMFcqLXhtm1Gep20iuIR3',
            name: 'SXTN',
            type: 'artist',
            uri: 'spotify:artist:0tMFcqLXhtm1Gep20iuIR3',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CW',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IL',
          'IN',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 235333,
        explicit: true,
        external_ids: {
          isrc: 'DEVX51700002',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/3wJT0nUXiJZc6lho16bYOp',
        },
        href: 'https://api.spotify.com/v1/tracks/3wJT0nUXiJZc6lho16bYOp',
        id: '3wJT0nUXiJZc6lho16bYOp',
        is_local: false,
        name: 'Er will Sex',
        popularity: 51,
        preview_url:
          'https://p.scdn.co/mp3-preview/4a8ad10a34d0d64084dea0ab9560bea405f8f9b9?cid=38b0480fd0224dc187294a0730ee8098',
        track_number: 2,
        type: 'track',
        uri: 'spotify:track:3wJT0nUXiJZc6lho16bYOp',
      },
      played_at: '2021-09-04T15:15:06.931Z',
      context: null,
    },
    {
      track: {
        album: {
          album_type: 'single',
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X',
              },
              href: 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X',
              id: '4q3ewBCX7sLwd24euuV69X',
              name: 'Bad Bunny',
              type: 'artist',
              uri: 'spotify:artist:4q3ewBCX7sLwd24euuV69X',
            },
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0EFisYRi20PTADoJrifHrz',
              },
              href: 'https://api.spotify.com/v1/artists/0EFisYRi20PTADoJrifHrz',
              id: '0EFisYRi20PTADoJrifHrz',
              name: 'Jhay Cortez',
              type: 'artist',
              uri: 'spotify:artist:0EFisYRi20PTADoJrifHrz',
            },
          ],
          available_markets: [
            'AD',
            'AE',
            'AG',
            'AL',
            'AM',
            'AO',
            'AR',
            'AT',
            'AU',
            'AZ',
            'BA',
            'BB',
            'BD',
            'BE',
            'BF',
            'BG',
            'BH',
            'BI',
            'BJ',
            'BN',
            'BO',
            'BR',
            'BS',
            'BT',
            'BW',
            'BY',
            'BZ',
            'CA',
            'CH',
            'CI',
            'CL',
            'CM',
            'CO',
            'CR',
            'CV',
            'CY',
            'CZ',
            'DE',
            'DJ',
            'DK',
            'DM',
            'DO',
            'DZ',
            'EC',
            'EE',
            'EG',
            'ES',
            'FI',
            'FJ',
            'FM',
            'FR',
            'GA',
            'GB',
            'GD',
            'GE',
            'GH',
            'GM',
            'GN',
            'GQ',
            'GR',
            'GT',
            'GW',
            'GY',
            'HK',
            'HN',
            'HR',
            'HT',
            'HU',
            'ID',
            'IE',
            'IL',
            'IN',
            'IS',
            'IT',
            'JM',
            'JO',
            'JP',
            'KE',
            'KG',
            'KH',
            'KI',
            'KM',
            'KN',
            'KR',
            'KW',
            'KZ',
            'LA',
            'LB',
            'LC',
            'LI',
            'LK',
            'LR',
            'LS',
            'LT',
            'LU',
            'LV',
            'MA',
            'MC',
            'MD',
            'ME',
            'MG',
            'MH',
            'MK',
            'ML',
            'MN',
            'MO',
            'MR',
            'MT',
            'MU',
            'MV',
            'MW',
            'MX',
            'MY',
            'MZ',
            'NA',
            'NE',
            'NG',
            'NI',
            'NL',
            'NO',
            'NP',
            'NR',
            'NZ',
            'OM',
            'PA',
            'PE',
            'PG',
            'PH',
            'PK',
            'PL',
            'PS',
            'PT',
            'PW',
            'PY',
            'QA',
            'RO',
            'RS',
            'RU',
            'RW',
            'SA',
            'SB',
            'SC',
            'SE',
            'SG',
            'SI',
            'SK',
            'SL',
            'SM',
            'SN',
            'SR',
            'ST',
            'SV',
            'SZ',
            'TD',
            'TG',
            'TH',
            'TL',
            'TN',
            'TO',
            'TR',
            'TT',
            'TV',
            'TW',
            'TZ',
            'UA',
            'UG',
            'US',
            'UY',
            'UZ',
            'VC',
            'VN',
            'VU',
            'WS',
            'XK',
            'ZA',
            'ZM',
            'ZW',
          ],
          external_urls: {
            spotify: 'https://open.spotify.com/album/43dl8hP5uNN9s6YeeJA5fv',
          },
          href: 'https://api.spotify.com/v1/albums/43dl8hP5uNN9s6YeeJA5fv',
          id: '43dl8hP5uNN9s6YeeJA5fv',
          images: [
            {
              height: 640,
              url: 'https://i.scdn.co/image/ab67616d0000b27334c8199b0b3b3fb42b8a98a8',
              width: 640,
            },
            {
              height: 300,
              url: 'https://i.scdn.co/image/ab67616d00001e0234c8199b0b3b3fb42b8a98a8',
              width: 300,
            },
            {
              height: 64,
              url: 'https://i.scdn.co/image/ab67616d0000485134c8199b0b3b3fb42b8a98a8',
              width: 64,
            },
          ],
          name: 'DÁKITI',
          release_date: '2020-10-30',
          release_date_precision: 'day',
          total_tracks: 1,
          type: 'album',
          uri: 'spotify:album:43dl8hP5uNN9s6YeeJA5fv',
        },
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4q3ewBCX7sLwd24euuV69X',
            },
            href: 'https://api.spotify.com/v1/artists/4q3ewBCX7sLwd24euuV69X',
            id: '4q3ewBCX7sLwd24euuV69X',
            name: 'Bad Bunny',
            type: 'artist',
            uri: 'spotify:artist:4q3ewBCX7sLwd24euuV69X',
          },
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0EFisYRi20PTADoJrifHrz',
            },
            href: 'https://api.spotify.com/v1/artists/0EFisYRi20PTADoJrifHrz',
            id: '0EFisYRi20PTADoJrifHrz',
            name: 'Jhay Cortez',
            type: 'artist',
            uri: 'spotify:artist:0EFisYRi20PTADoJrifHrz',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AG',
          'AL',
          'AM',
          'AO',
          'AR',
          'AT',
          'AU',
          'AZ',
          'BA',
          'BB',
          'BD',
          'BE',
          'BF',
          'BG',
          'BH',
          'BI',
          'BJ',
          'BN',
          'BO',
          'BR',
          'BS',
          'BT',
          'BW',
          'BY',
          'BZ',
          'CA',
          'CH',
          'CI',
          'CL',
          'CM',
          'CO',
          'CR',
          'CV',
          'CY',
          'CZ',
          'DE',
          'DJ',
          'DK',
          'DM',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FJ',
          'FM',
          'FR',
          'GA',
          'GB',
          'GD',
          'GE',
          'GH',
          'GM',
          'GN',
          'GQ',
          'GR',
          'GT',
          'GW',
          'GY',
          'HK',
          'HN',
          'HR',
          'HT',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JM',
          'JO',
          'JP',
          'KE',
          'KG',
          'KH',
          'KI',
          'KM',
          'KN',
          'KR',
          'KW',
          'KZ',
          'LA',
          'LB',
          'LC',
          'LI',
          'LK',
          'LR',
          'LS',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MD',
          'ME',
          'MG',
          'MH',
          'MK',
          'ML',
          'MN',
          'MO',
          'MR',
          'MT',
          'MU',
          'MV',
          'MW',
          'MX',
          'MY',
          'MZ',
          'NA',
          'NE',
          'NG',
          'NI',
          'NL',
          'NO',
          'NP',
          'NR',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PG',
          'PH',
          'PK',
          'PL',
          'PS',
          'PT',
          'PW',
          'PY',
          'QA',
          'RO',
          'RS',
          'RU',
          'RW',
          'SA',
          'SB',
          'SC',
          'SE',
          'SG',
          'SI',
          'SK',
          'SL',
          'SM',
          'SN',
          'SR',
          'ST',
          'SV',
          'SZ',
          'TD',
          'TG',
          'TH',
          'TL',
          'TN',
          'TO',
          'TR',
          'TT',
          'TV',
          'TW',
          'TZ',
          'UA',
          'UG',
          'US',
          'UY',
          'UZ',
          'VC',
          'VN',
          'VU',
          'WS',
          'XK',
          'ZA',
          'ZM',
          'ZW',
        ],
        disc_number: 1,
        duration_ms: 205090,
        explicit: true,
        external_ids: {
          isrc: 'QMFME2004132',
        },
        external_urls: {
          spotify: 'https://open.spotify.com/track/47EiUVwUp4C9fGccaPuUCS',
        },
        href: 'https://api.spotify.com/v1/tracks/47EiUVwUp4C9fGccaPuUCS',
        id: '47EiUVwUp4C9fGccaPuUCS',
        is_local: false,
        name: 'DÁKITI',
        popularity: 83,
        preview_url:
          'https://p.scdn.co/mp3-preview/edd9bea2e66b14169f8bbfa45a78b6599b14160a?cid=38b0480fd0224dc187294a0730ee8098',
        track_number: 1,
        type: 'track',
        uri: 'spotify:track:47EiUVwUp4C9fGccaPuUCS',
      },
      played_at: '2021-09-04T15:11:10.551Z',
      context: null,
    },
  ],
  next: 'https://api.spotify.com/v1/me/player/recently-played?after=1630768819797&limit=3',
  cursors: {
    after: '1630768819797',
    before: '1630768270551',
  },
  limit: 3,
  href: 'https://api.spotify.com/v1/me/player/recently-played?after=1&limit=3',
};
