name: CI Handler Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: yarn install:ci

      # Only run the coverage once
      # https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa
      - name: Run tests and get coverage
        run: |
          SUMMARY="$(yarn test --coverage --coverageReporters='text-summary' | tail -3 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6a89dcb0ccbc9b64058e7c6a426c6ccb
          filename: spotify_history_coverage.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest
