name: CI Handler Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Matrix
    strategy:
      matrix:
        node-version: [14.17.4]

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Read node version from .nvmrc
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
          with:
            node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn install:ci

      # Only run the coverage once
      # https://dev.to/thejaredwilcurt/coverage-badge-with-github-actions-finally-59fa
      - name: Run tests and get coverage
        run: |
          SUMMARY="$(yarn test --coverage --coverageReporters='text-summary' | tail -3 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 6a89dcb0ccbc9b64058e7c6a426c6ccb
          filename: spotify_history_coverage.json
          label: Coverage
          message: ${{ env.COVERAGE }}
          color: green
          namedLogo: jest
